[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

# [git_commit]
# tag_symbol = " tag "

# [git_status]
# ahead = ">"
# behind = "<"
# diverged = "<>"
# renamed = "r"
# deleted = "x"

[aws]
symbol = "aws "

[directory]
read_only = " "

[docker_context]
symbol = "docker "
disabled = true

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[kubernetes]
disabled = false

[nodejs]
symbol = "nodejs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "
