# [character]
# success_symbol = "[>](bold green)"
# error_symbol = "[x](bold red)"
# vimcmd_symbol = "[<](bold green)"

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #f8f8f2)"

[aws]
symbol = " "

[directory]
read_only = " "
# style = "fg:#DA627D"
style = "bold #50fa7b"

[docker_context]
symbol = "docker "
disabled = true

[git_branch]
style = "bold green"

[git_commit]
tag_symbol = " tag "

[git_metrics]
disabled = false

[git_status]
disabled = false
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[golang]
symbol = " "

[kubernetes]
disabled = false

[nodejs]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "
